# version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: selfglow-db
    restart: always
    environment:
      POSTGRES_USER: selfglow_user
      POSTGRES_PASSWORD: selfglow_password
      POSTGRES_DB: selfglow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: